version: '3.7'

services:
  php:
    container_name: "${PHP_CONTAINER_NAME}"
    build:
      context: ./php
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - ${APP_FOLDER}:/var/www

  nginx:
    container_name: "${NGINX_CONTAINER_NAME}"
    build:
      context: ./nginx
    volumes:
      - ${APP_FOLDER}:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    ports:
      - "${APP_PORT_MAPPING}"